# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boola', '0003_auto_20161031_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pe', 'pending'), ('co', 'Confirmed'), ('ca', 'Cancelled')], default='pending', max_length=32),
        ),
    ]
