# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boola', '0004_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='confirmed',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pe', 'Pending'), ('co', 'Confirmed'), ('ca', 'Cancelled')], default='pending', max_length=32),
        ),
    ]
