# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciple', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='in_transit',
            field=models.BooleanField(default=False, verbose_name='out of office?'),
        ),
    ]
