# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boola', '0001_initial'),
        ('disciple', '0002_disk_in_transit'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boola.Content'),
        ),
    ]
