# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boola', '0001_initial'),
        ('disciple', '0003_disk_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boola.Client')),
                ('disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciple.Disk')),
            ],
        ),
    ]
