# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciple', '0005_auto_20161014_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
