# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciple', '0006_disk_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disk',
            options={'ordering': ('name',)},
        ),
    ]
