# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciple', '0008_remove_disk_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='client',
        ),
    ]
